apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: ghcr.io/pab1it0/prometheus-mcp-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus:9090"
        - name: PROMETHEUS_MCP_SERVER_TRANSPORT
          value: "http"
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - -H
            - "Accept: text/event-stream"
            - http://localhost:8080/mcp
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          retries: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
